### ISSUE TITLE
local variable 'd1' referenced before assignment

### ISSUE THREAD

**Issue by weilongMao** [azusakou/SMESwin-Unet#2]
File "/mnt/data/mwl/unet/SMESwinModel/swin_transformer_unet_skip_expand_decoder_sys.py", line 806, in forward
    d0, d1, d2, d3, w = self.mcct(d0, self.skipshape(d1), self.skipshape(d2), self.skipshape(d3))
UnboundLocalError: local variable 'd1' referenced before assignment

**Comment by azusakou** [comment]
Many thanks! Sorry for my mistake, now it works.
